#include "common.h"

#include <stdint.h>

#define TEST_OPIVVV(op, type2, type1, type_ret, lmul) \
printf("\ntest " #op "_vv_" #type_ret #lmul " ...\n"); \
test_opivvv<type_ret, type2, type1>(op ## _vv_ref<type_ret, type2, type1>, op ## _vv_## type_ret ## lmul ## _vec)

#define TEST_OPIVVV_M(op, type2, type1, type_ret, lmul) \
printf("\ntest " #op "_vv_" #type_ret #lmul "_m" " ...\n"); \
test_opivvv_m<type_ret, type2, type1>(op ## _vv_m_ref<type_ret, type2, type1>, op ## _vv_## type_ret ## lmul ## _m_vec)

#define TEST_OPIVVV_GROUP(op)     TEST_OPI3OPS_COMMON_GROUP(TEST_OPIVVV, op)
#define TEST_OPIVVV_III_GROUP(op) TEST_OPI3OPS_COMMON_III_GROUP(TEST_OPIVVV, op)
#define TEST_OPIVVV_UUU_GROUP(op) TEST_OPI3OPS_COMMON_UUU_GROUP(TEST_OPIVVV, op)
#define TEST_OPIVVV_IUI_GROUP(op) TEST_OPI3OPS_COMMON_IUI_GROUP(TEST_OPIVVV, op)

#define TEST_OPIVVV_III_GROUP_MF8(op) TEST_OPI3OPS_COMMON_III_GROUP_MF8(TEST_OPIVVV, op)
#define TEST_OPIVVV_III_GROUP_MF4(op) TEST_OPI3OPS_COMMON_III_GROUP_MF4(TEST_OPIVVV, op)
#define TEST_OPIVVV_III_GROUP_MF2(op) TEST_OPI3OPS_COMMON_III_GROUP_MF2(TEST_OPIVVV, op)
#define TEST_OPIVVV_III_GROUP_M1(op)  TEST_OPI3OPS_COMMON_III_GROUP_M1(TEST_OPIVVV, op)
#define TEST_OPIVVV_III_GROUP_M2(op)  TEST_OPI3OPS_COMMON_III_GROUP_M2(TEST_OPIVVV, op)
#define TEST_OPIVVV_III_GROUP_M4(op)  TEST_OPI3OPS_COMMON_III_GROUP_M4(TEST_OPIVVV, op)
#define TEST_OPIVVV_III_GROUP_M8(op)  TEST_OPI3OPS_COMMON_III_GROUP_M8(TEST_OPIVVV, op)
#define TEST_OPIVVV_UUU_GROUP_MF8(op) TEST_OPI3OPS_COMMON_UUU_GROUP_MF8(TEST_OPIVVV, op)
#define TEST_OPIVVV_UUU_GROUP_MF4(op) TEST_OPI3OPS_COMMON_UUU_GROUP_MF4(TEST_OPIVVV, op)
#define TEST_OPIVVV_UUU_GROUP_MF2(op) TEST_OPI3OPS_COMMON_UUU_GROUP_MF2(TEST_OPIVVV, op)
#define TEST_OPIVVV_UUU_GROUP_M1(op)  TEST_OPI3OPS_COMMON_UUU_GROUP_M1(TEST_OPIVVV, op)
#define TEST_OPIVVV_UUU_GROUP_M2(op)  TEST_OPI3OPS_COMMON_UUU_GROUP_M2(TEST_OPIVVV, op)
#define TEST_OPIVVV_UUU_GROUP_M4(op)  TEST_OPI3OPS_COMMON_UUU_GROUP_M4(TEST_OPIVVV, op)
#define TEST_OPIVVV_UUU_GROUP_M8(op)  TEST_OPI3OPS_COMMON_UUU_GROUP_M8(TEST_OPIVVV, op)
#define TEST_OPIVVV_IUI_GROUP_MF8(op) TEST_OPI3OPS_COMMON_IUI_GROUP_MF8(TEST_OPIVVV, op)
#define TEST_OPIVVV_IUI_GROUP_MF4(op) TEST_OPI3OPS_COMMON_IUI_GROUP_MF4(TEST_OPIVVV, op)
#define TEST_OPIVVV_IUI_GROUP_MF2(op) TEST_OPI3OPS_COMMON_IUI_GROUP_MF2(TEST_OPIVVV, op)
#define TEST_OPIVVV_IUI_GROUP_M1(op)  TEST_OPI3OPS_COMMON_IUI_GROUP_M1(TEST_OPIVVV, op)
#define TEST_OPIVVV_IUI_GROUP_M2(op)  TEST_OPI3OPS_COMMON_IUI_GROUP_M2(TEST_OPIVVV, op)
#define TEST_OPIVVV_IUI_GROUP_M4(op)  TEST_OPI3OPS_COMMON_IUI_GROUP_M4(TEST_OPIVVV, op)
#define TEST_OPIVVV_IUI_GROUP_M8(op)  TEST_OPI3OPS_COMMON_IUI_GROUP_M8(TEST_OPIVVV, op)

#define TEST_OPIVVV_M_GROUP(op)     TEST_OPI3OPS_COMMON_GROUP(TEST_OPIVVV_M, op)
#define TEST_OPIVVV_III_M_GROUP(op) TEST_OPI3OPS_COMMON_III_GROUP(TEST_OPIVVV_M, op)
#define TEST_OPIVVV_UUU_M_GROUP(op) TEST_OPI3OPS_COMMON_UUU_GROUP(TEST_OPIVVV_M, op)
#define TEST_OPIVVV_IUI_M_GROUP(op) TEST_OPI3OPS_COMMON_IUI_GROUP(TEST_OPIVVV_M, op)

#define TEST_OPIVVV_III_M_GROUP_MF8(op) TEST_OPI3OPS_COMMON_III_GROUP_MF8( TEST_OPIVVV_M, op)
#define TEST_OPIVVV_III_M_GROUP_MF4(op) TEST_OPI3OPS_COMMON_III_GROUP_MF4( TEST_OPIVVV_M, op)
#define TEST_OPIVVV_III_M_GROUP_MF2(op) TEST_OPI3OPS_COMMON_III_GROUP_MF2( TEST_OPIVVV_M, op)
#define TEST_OPIVVV_III_M_GROUP_M1(op)  TEST_OPI3OPS_COMMON_III_GROUP_M1(  TEST_OPIVVV_M, op)
#define TEST_OPIVVV_III_M_GROUP_M2(op)  TEST_OPI3OPS_COMMON_III_GROUP_M2(  TEST_OPIVVV_M, op)
#define TEST_OPIVVV_III_M_GROUP_M4(op)  TEST_OPI3OPS_COMMON_III_GROUP_M4(  TEST_OPIVVV_M, op)
#define TEST_OPIVVV_III_M_GROUP_M8(op)  TEST_OPI3OPS_COMMON_III_GROUP_M8(  TEST_OPIVVV_M, op)
#define TEST_OPIVVV_UUU_M_GROUP_MF8(op) TEST_OPI3OPS_COMMON_UUU_GROUP_MF8( TEST_OPIVVV_M, op)
#define TEST_OPIVVV_UUU_M_GROUP_MF4(op) TEST_OPI3OPS_COMMON_UUU_GROUP_MF4( TEST_OPIVVV_M, op)
#define TEST_OPIVVV_UUU_M_GROUP_MF2(op) TEST_OPI3OPS_COMMON_UUU_GROUP_MF2( TEST_OPIVVV_M, op)
#define TEST_OPIVVV_UUU_M_GROUP_M1(op)  TEST_OPI3OPS_COMMON_UUU_GROUP_M1(  TEST_OPIVVV_M, op)
#define TEST_OPIVVV_UUU_M_GROUP_M2(op)  TEST_OPI3OPS_COMMON_UUU_GROUP_M2(  TEST_OPIVVV_M, op)
#define TEST_OPIVVV_UUU_M_GROUP_M4(op)  TEST_OPI3OPS_COMMON_UUU_GROUP_M4(  TEST_OPIVVV_M, op)
#define TEST_OPIVVV_UUU_M_GROUP_M8(op)  TEST_OPI3OPS_COMMON_UUU_GROUP_M8(  TEST_OPIVVV_M, op)
#define TEST_OPIVVV_IUI_M_GROUP_MF8(op) TEST_OPI3OPS_COMMON_IUI_GROUP_MF8( TEST_OPIVVV_M, op)
#define TEST_OPIVVV_IUI_M_GROUP_MF4(op) TEST_OPI3OPS_COMMON_IUI_GROUP_MF4( TEST_OPIVVV_M, op)
#define TEST_OPIVVV_IUI_M_GROUP_MF2(op) TEST_OPI3OPS_COMMON_IUI_GROUP_MF2( TEST_OPIVVV_M, op)
#define TEST_OPIVVV_IUI_M_GROUP_M1(op)  TEST_OPI3OPS_COMMON_IUI_GROUP_M1(  TEST_OPIVVV_M, op)
#define TEST_OPIVVV_IUI_M_GROUP_M2(op)  TEST_OPI3OPS_COMMON_IUI_GROUP_M2(  TEST_OPIVVV_M, op)
#define TEST_OPIVVV_IUI_M_GROUP_M4(op)  TEST_OPI3OPS_COMMON_IUI_GROUP_M4(  TEST_OPIVVV_M, op)
#define TEST_OPIVVV_IUI_M_GROUP_M8(op)  TEST_OPI3OPS_COMMON_IUI_GROUP_M8(  TEST_OPIVVV_M, op)



