#ifndef __TDEF_OPI_VVMV_H__
#define __TDEF_OPI_VVMV_H__

#include "common.h"
#include "opi_vvv.h"

#define test_opi_vvmv test_opi_vvv_m

#define TEST_OPI_VVMV(op, type2, type1, type_ret, lmul) \
printf("\ntest " #op "_vvm_" #type_ret #lmul " ...\n"); \
test_opi_vvmv<type_ret, type2, type1>(op ## _vvm_ref<type_ret, type2, type1>, op ## _vvm_## type_ret ## lmul ## _vec, TEST_LENGTH)

#define TEST_OPI_VVMV_GROUP(op)         TEST_OPI3OPS_COMMON_GROUP(TEST_OPI_VVMV, op)
#define TEST_OPI_VVMV_III_GROUP(op)     TEST_OPI3OPS_COMMON_III_GROUP(TEST_OPI_VVMV, op)
#define TEST_OPI_VVMV_IUI_GROUP(op)     TEST_OPI3OPS_COMMON_IUI_GROUP(TEST_OPI_VVMV, op)
#define TEST_OPI_VVMV_UUU_GROUP(op)     TEST_OPI3OPS_COMMON_UUU_GROUP(TEST_OPI_VVMV, op)
#define TEST_OPI_VVMV_III_GROUP_MF8(op) TEST_OPI3OPS_COMMON_III_GROUP_MF8(TEST_OPI_VVMV, op)
#define TEST_OPI_VVMV_III_GROUP_MF4(op) TEST_OPI3OPS_COMMON_III_GROUP_MF4(TEST_OPI_VVMV, op)
#define TEST_OPI_VVMV_III_GROUP_MF2(op) TEST_OPI3OPS_COMMON_III_GROUP_MF2(TEST_OPI_VVMV, op)
#define TEST_OPI_VVMV_III_GROUP_M1(op)  TEST_OPI3OPS_COMMON_III_GROUP_M1(TEST_OPI_VVMV, op)
#define TEST_OPI_VVMV_III_GROUP_M2(op)  TEST_OPI3OPS_COMMON_III_GROUP_M2(TEST_OPI_VVMV, op)
#define TEST_OPI_VVMV_III_GROUP_M4(op)  TEST_OPI3OPS_COMMON_III_GROUP_M4(TEST_OPI_VVMV, op)
#define TEST_OPI_VVMV_III_GROUP_M8(op)  TEST_OPI3OPS_COMMON_III_GROUP_M8(TEST_OPI_VVMV, op)
#define TEST_OPI_VVMV_UUU_GROUP_MF8(op) TEST_OPI3OPS_COMMON_UUU_GROUP_MF8(TEST_OPI_VVMV, op)
#define TEST_OPI_VVMV_UUU_GROUP_MF4(op) TEST_OPI3OPS_COMMON_UUU_GROUP_MF4(TEST_OPI_VVMV, op)
#define TEST_OPI_VVMV_UUU_GROUP_MF2(op) TEST_OPI3OPS_COMMON_UUU_GROUP_MF2(TEST_OPI_VVMV, op)
#define TEST_OPI_VVMV_UUU_GROUP_M1(op)  TEST_OPI3OPS_COMMON_UUU_GROUP_M1(TEST_OPI_VVMV, op)
#define TEST_OPI_VVMV_UUU_GROUP_M2(op)  TEST_OPI3OPS_COMMON_UUU_GROUP_M2(TEST_OPI_VVMV, op)
#define TEST_OPI_VVMV_UUU_GROUP_M4(op)  TEST_OPI3OPS_COMMON_UUU_GROUP_M4(TEST_OPI_VVMV, op)
#define TEST_OPI_VVMV_UUU_GROUP_M8(op)  TEST_OPI3OPS_COMMON_UUU_GROUP_M8(TEST_OPI_VVMV, op)
#define TEST_OPI_VVMV_IUI_GROUP_MF8(op) TEST_OPI3OPS_COMMON_IUI_GROUP_MF8(TEST_OPI_VVMV, op)
#define TEST_OPI_VVMV_IUI_GROUP_MF4(op) TEST_OPI3OPS_COMMON_IUI_GROUP_MF4(TEST_OPI_VVMV, op)
#define TEST_OPI_VVMV_IUI_GROUP_MF2(op) TEST_OPI3OPS_COMMON_IUI_GROUP_MF2(TEST_OPI_VVMV, op)
#define TEST_OPI_VVMV_IUI_GROUP_M1(op)  TEST_OPI3OPS_COMMON_IUI_GROUP_M1(TEST_OPI_VVMV, op)
#define TEST_OPI_VVMV_IUI_GROUP_M2(op)  TEST_OPI3OPS_COMMON_IUI_GROUP_M2(TEST_OPI_VVMV, op)
#define TEST_OPI_VVMV_IUI_GROUP_M4(op)  TEST_OPI3OPS_COMMON_IUI_GROUP_M4(TEST_OPI_VVMV, op)
#define TEST_OPI_VVMV_IUI_GROUP_M8(op)  TEST_OPI3OPS_COMMON_IUI_GROUP_M8(TEST_OPI_VVMV, op)

#define TEST_OPI_VVMV_ALL() \
TEST_OPI_VVMV_GROUP(vmerge) \
TEST_OPI_VVMV_GROUP(vadc) \
TEST_OPI_VVMV_GROUP(vsbc) \

#endif
