#ifndef __TDEF_OPI_VXMV_H__
#define __TDEF_OPI_VXMV_H__

#include "common.h"
#include "opi_vxv.h"

#define test_opi_vxmv test_opi_vxv_m

#define TEST_OPI_VXMV(op, type, lmul) \
printf("\ntest " #op "_vxm_" #type #lmul " ...\n"); \
test_opi_vxmv<type, type, type>(op ## _vxm_ref<type, type, type>, op ## _vxm_## type ## lmul ## _vec, TEST_LENGTH)

#define TEST_OPI_VXMV_GROUP(op)         TEST_OPI1OP_COMMON_GROUP(TEST_OPI_VXMV, op)
#define TEST_OPI_VXMV_III_GROUP(op)     TEST_OPI1OP_COMMON_I_GROUP(TEST_OPI_VXMV, op)
#define TEST_OPI_VXMV_UUU_GROUP(op)     TEST_OPI1OP_COMMON_U_GROUP(TEST_OPI_VXMV, op)
#define TEST_OPI_VXMV_III_GROUP_MF8(op) TEST_OPI1OP_COMMON_I_GROUP_MF8(TEST_OPI_VXMV, op)
#define TEST_OPI_VXMV_III_GROUP_MF4(op) TEST_OPI1OP_COMMON_I_GROUP_MF4(TEST_OPI_VXMV, op)
#define TEST_OPI_VXMV_III_GROUP_MF2(op) TEST_OPI1OP_COMMON_I_GROUP_MF2(TEST_OPI_VXMV, op)
#define TEST_OPI_VXMV_III_GROUP_M1(op)  TEST_OPI1OP_COMMON_I_GROUP_M1(TEST_OPI_VXMV, op)
#define TEST_OPI_VXMV_III_GROUP_M2(op)  TEST_OPI1OP_COMMON_I_GROUP_M2(TEST_OPI_VXMV, op)
#define TEST_OPI_VXMV_III_GROUP_M4(op)  TEST_OPI1OP_COMMON_I_GROUP_M4(TEST_OPI_VXMV, op)
#define TEST_OPI_VXMV_III_GROUP_M8(op)  TEST_OPI1OP_COMMON_I_GROUP_M8(TEST_OPI_VXMV, op)
#define TEST_OPI_VXMV_UUU_GROUP_MF8(op) TEST_OPI1OP_COMMON_U_GROUP_MF8(TEST_OPI_VXMV, op)
#define TEST_OPI_VXMV_UUU_GROUP_MF4(op) TEST_OPI1OP_COMMON_U_GROUP_MF4(TEST_OPI_VXMV, op)
#define TEST_OPI_VXMV_UUU_GROUP_MF2(op) TEST_OPI1OP_COMMON_U_GROUP_MF2(TEST_OPI_VXMV, op)
#define TEST_OPI_VXMV_UUU_GROUP_M1(op)  TEST_OPI1OP_COMMON_U_GROUP_M1(TEST_OPI_VXMV, op)
#define TEST_OPI_VXMV_UUU_GROUP_M2(op)  TEST_OPI1OP_COMMON_U_GROUP_M2(TEST_OPI_VXMV, op)
#define TEST_OPI_VXMV_UUU_GROUP_M4(op)  TEST_OPI1OP_COMMON_U_GROUP_M4(TEST_OPI_VXMV, op)
#define TEST_OPI_VXMV_UUU_GROUP_M8(op)  TEST_OPI1OP_COMMON_U_GROUP_M8(TEST_OPI_VXMV, op)

#define TEST_OPI_VXMV_ALL() \
TEST_OPI_VXMV_GROUP(vmerge) \
TEST_OPI_VXMV_GROUP(vadc) \
TEST_OPI_VXMV_GROUP(vsbc) \

#endif
